const Koa = require('koa')
const kf = require('kf-router')
const fs = require('fs')
const app = new Koa()

app.use(require('./middleware/params.js'))
app.use(require('./middleware/return.js'))
app.use(require('./middleware/mysql.js'))
app.use(require('./middleware/cors.js'))
app.use(kf())
app.listen(3000)
